# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: push news to Biligame

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 16 * * 4'
    - cron: '0 16 * * 0-3,5,6'

permissions:
  contents: read

jobs:
  Wiki_push:
    name: Wiki push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        architecture: 'x64'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --statistics --ignore=E501,C901
    - name: Run script
      env:
        LGPASSWORD: ${{ secrets.LGPASSWORD }}
        SESSDATA: ${{ secrets.SESSDATA }}
      run: |
        python bwiki_job.py "${{ github.event.schedule }}" "${LGPASSWORD}" "${SESSDATA}"
